@ShippingPricingService_HostAddress = http://localhost:5075

GET {{ShippingPricingService_HostAddress}}/health
Accept: application/json

###

POST {{ShippingPricingService_HostAddress}}/shipping-prices/quotes/batch
Content-Type: application/json

{
  "buyerId": "046776ea-44ca-4921-8f18-6cce4d0848f8",
  "sellerId": "26937f31-12b4-457c-826f-f1df41a03d17",
  "destinationPostalCode": "05726-100",
  "cartTotal": 349.90,
  "currency": "BRL",
  "requestedAtUtc": "2026-06-08T16:00:00Z",
  "candidates": [
    {
      "candidateId": "route-1",
      "routeId": "route_a13f22",
      "originNodeId": "db082eda-6e8d-4eb8-9c18-70002da6fc97",
      "carrierCode": "MELI-LOGISTICS",
      "serviceLevelCode": "EXPRESS",
      "package": {
        "actualWeightKg": 4.2,
        "cubicWeightKg": 6.8,
        "isFragile": false,
        "isRestricted": false,
        "category": "electronics"
      }
    }
  ]
}
